import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppQuery from "./frontend/src/providers/AppQuery";
import AppContextUser from "./frontend/src/providers/AppContextUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <AppContextUser>
          <AppQuery>{children}</AppQuery>
        </AppContextUser>
      </body>
    </html>
  );
}
